[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=5
    -DCONFIG_LOG_MAXIMUM_LEVEL_VERBOSE=y
    -DCONFIG_LOG_MAXIMUM_LEVEL=5
    -DARDUINO_ARCH_ESP32=1
lib_deps = 
    FastLED
    IRRemote

[platformio]
default_envs = esp32c3
